apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 07-plane-migrator.yaml
  - 08-plane-api.yaml
  - 08-rocketchat.yaml
  - 09-plane-worker.yaml
  - 09-ingress.yaml
  - 10-plane-beat.yaml
  - 11-plane-live.yaml
  - 12-plane-web.yaml
  - 14-plane-admin-space.yaml

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value: [{name: ghcr-pull-secret}]
  - target:
      kind: Job
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value: [{name: ghcr-pull-secret}]